### ISSUE TITLE
Cannot read property 'subtle' of undefined

### ISSUE THREAD

**Issue by tungnnt** [makiprogrammer/ts-messenger-api#13]
**Describe the bug**
I cannot run the example code, it throws Error: Cannot read property 'subtle' of undefined

**To Reproduce**
Just copy the example code in repo, replace with my credential, then run.

**Expected behavior**
It should login successfully

**Environment (please complete the following information):**
 - OS: Linux
 - Node version: v14.15.0
 - ts-messenger-api package version: latest

**Comment by KMatuszak** [comment]
```
Note: This package works only on NodeJS v15 and higher!
```

try upgrading your node version
