### ISSUE TITLE
sendMessage() resolves before message is sent

### ISSUE THREAD

**Issue by adamhl8** [makiprogrammer/ts-messenger-api#15]
**Describe the bug**
I might be missing something/doing something dumb, but it seems like `sendMessage()` resolves its promise before actually sending the message.

**To Reproduce**
```
// login stuff

await api.listen();
await api.sendMessage({ body: 'Hi' }, friends[0].id);
process.exit(0) // Exit immediately after sending message.
// Message never actually gets sent.
```

**Expected behavior**
`sendMessage()` fully sends message before resolving.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node version: v16.4.1
- ts-messenger-api package version: latest

**Comment by hoangvu12** [comment]
I don't think you will know if the message sent...
